"""Migration 1, automaticaslly generated"""

# Generated by Django 5.0.6 on 2024-06-15 16:28

from django.db import migrations


class Migration(migrations.Migration):
    """Migration"""

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="guest_can_skip",
            new_name="votes_to_skip",
        ),
    ]
